# Stage 1: Build frontend
FROM node:22.23-alpine AS build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./

# Utilise le package-lock et conserve le cache npm entre les builds
RUN --mount=type=cache,target=/root/.npm \
    npm ci --prefer-offline

COPY frontend/ .
RUN npm run build


# Stage 2: Production nginx
FROM nginx:1.31.6-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]